version: '3.7'
services:
  gateway:
    build:
        context: ..
        dockerfile: ./DockerfileGatewayAPI
    restart: always 
    ports:
    - "5000:80"
    networks:
     - ec_backend_2k20_dev
  userservice:
    build:
        context: ..
        dockerfile: ./DockerfileEmail
    restart: always 
    ports:
    - "5005:80"
    networks:
     - ec_backend_2k20_dev
networks:  
  ec_backend_2k20_dev:
    driver: bridge
    name: ec_backend_2k20_dev